// DUTCH BASS EXPORTS

export { default as fifthSaw } from "./dutch-bass/5th Saw.json";
export { default as Delayed } from "./dutch-bass/Delayed.json";
export { default as LeidenLoop } from "./dutch-bass/Leiden Loop.json";
export { default as ShapeShifter } from "./dutch-bass/ShapeShifter.json";
export { default as VintageKit } from "./dutch-bass/Vintage Kit.json";
export { default as NinetiesClassic } from "./dutch-bass/90'S Classic.json";
export { default as DeltaBass } from "./dutch-bass/Delta Bass.json";
export { default as MiniBass } from "./dutch-bass/Mini Bass.json";
export { default as SimpleBeat } from "./dutch-bass/Simple Beat.json";
export { default as VinylPulse } from "./dutch-bass/Vinyl Pulse.json";
export { default as AcidVox } from "./dutch-bass/Acid Vox.json";
export { default as DutchClassic } from "./dutch-bass/DutchClassic.json";
export { default as MotorMouth } from "./dutch-bass/Motor Mouth.json";
export { default as SoulFood } from "./dutch-bass/Soul Food.json";
export { default as VocalChordz } from "./dutch-bass/Vocal Chordz.json";
export { default as AnalogDrums } from "./dutch-bass/Analog Drums.json";
export { default as ElectroKit } from "./dutch-bass/Electro Kit.json";
export { default as MrMatrix } from "./dutch-bass/Mr Matrix.json";
export { default as SyntheBass } from "./dutch-bass/Synthe Bass.json";
export { default as Boogie80s } from "./dutch-bass/Boogie 80's.json";
export { default as FunkyAcid } from "./dutch-bass/Funky Acid.json";
export { default as PortaBass } from "./dutch-bass/Porta Bass.json";
export { default as TechNoir } from "./dutch-bass/Tech Noir.json";
export { default as DanceBass } from "./dutch-bass/Dance Bass.json";
export { default as GrittySquare } from "./dutch-bass/GrittySquare.json";
export { default as PunkFunk } from "./dutch-bass/Punk Funk.json";
export { default as VCTenVox } from "./dutch-bass/VC-10 Vox.json";
export { default as DeepHouse } from "./dutch-bass/Deep House.json";
export { default as KeycityBass } from "./dutch-bass/Keycity Bass.json";
export { default as RawBass } from "./dutch-bass/Raw Bass.json";
export { default as VideoGame } from "./dutch-bass/Video Game.json";

// DUTCH BASS END ^

//

// DEFAULTS FOLDER EXPORTS V

export { default as Digisnd } from "./defaults/< Digisnd >.json";
export { default as fifthBrass } from "./defaults/<5th brASs>.json";
export { default as afxBass } from "./defaults/<AFX> bAss.json";
export { default as Ardkore92 } from "./defaults/<Ardkore92>.json";
export { default as Duophony } from "./defaults/<Duophony>.json";
export { default as Flute } from "./defaults/<Flute>.json";
export { default as HarmonBa } from "./defaults/<HarmonBa>.json";
export { default as MTdigArp } from "./defaults/<MT-digArp>.json";
export { default as PWMenvBA } from "./defaults/<PWM envBA>.json";
export { default as Ratewobble } from "./defaults/<Ratewobble.json";
export { default as SyncLAM } from "./defaults/<SyncLAM>.json";
export { default as SyncMtion } from "./defaults/<SyncMtion>.json";
export { default as afxAcid } from "./defaults/<afx acid3>.json";
export { default as afxBeat } from "./defaults/<afx beat>.json";
export { default as akunk } from "./defaults/<akunk b>.json";
export { default as aliasBass } from "./defaults/<aliasBass>.json";
export { default as ascension } from "./defaults/<ascension>.json";
export { default as beatAndBass } from "./defaults/<beat&bass>.json";
export { default as bnsbeats1 } from "./defaults/<bnsbeats1>.json";
export { default as bnsbeats2 } from "./defaults/<bnsbeats2>.json";
export { default as bnsbeats3 } from "./defaults/<bnsbeats3>.json";
export { default as bnsbeats4 } from "./defaults/<bnsbeats4>.json";
export { default as bnsbeats5 } from "./defaults/<bnsbeats5>.json";
export { default as centipede } from "./defaults/<centipede>.json";
export { default as deepBass } from "./defaults/<deep bass>.json";
export { default as epicAcid } from "./defaults/<epic acid>.json";
export { default as model800 } from "./defaults/<model 800>.json";
export { default as phaseClks } from "./defaults/<phaseClks>.json";
export { default as wavetable } from "./defaults/<wavetable>.json";
export { default as xocPlay } from "./defaults/<xoc PLAY>.json";
export { default as Anfem } from "./defaults/Anfem.json";
export { default as ArcLead } from "./defaults/Arc Lead.json";
export { default as ArpmeLead } from "./defaults/Arpme Lead.json";
export { default as BitterLead } from "./defaults/BitterLead.json";
export { default as Bosshog } from "./defaults/Bosshog.json";
export { default as BouncyBalls } from "./defaults/Bouncy Balls.json";
export { default as BrokenArcade } from "./defaults/BrokenArcade.json";
export { default as Childhood } from "./defaults/Childhood.json";
export { default as Chopchoon } from "./defaults/Chopchoon.json";
export { default as CpuCycles } from "./defaults/Cpu Cycles.json";
export { default as Dambuster } from "./defaults/Dambuster.json";
export { default as DarkPerc } from "./defaults/Dark Perc.json";
export { default as DirtySub } from "./defaults/Dirty Sub.json";
export { default as Disemvowel } from "./defaults/Disemvowel.json";
export { default as DistortedSqr } from "./defaults/DistortedSqr.json";
export { default as DrJuice } from "./defaults/Dr.Juice.json";
export { default as DualSaw } from "./defaults/Dual Saw.json";
export { default as FmodSeq } from "./defaults/FMod Seq.json";
export { default as Fake30SC } from "./defaults/Fake3OSC.json";
export { default as GhostTown } from "./defaults/Ghost Town.json";
export { default as HardRun } from "./defaults/Hard Run.json";
export { default as HerdOfCrab } from "./defaults/Herd Of Crab.json";
export { default as HoodieBass } from "./defaults/Hoodie Bass.json";
export { default as Injection } from "./defaults/Injection.json";
export { default as Jackathon } from "./defaults/Jackathon.json";
export { default as JungleSub } from "./defaults/Jungle Sub.json";
export { default as Lfoiled } from "./defaults/Lfoiled.json";
export { default as LittleGlitch } from "./defaults/LittleGlitch.json";
export { default as LoudSiren } from "./defaults/Loud Siren.json";
export { default as LuFuki } from "./defaults/Lu-Fuki.json";
export { default as MilkyWay } from "./defaults/Milky Way.json";
export { default as MonoBrass } from "./defaults/Mono Brass.json";
export { default as OiOi } from "./defaults/OIOI.json";
export { default as OnTheMoon } from "./defaults/On the Moon.json";
export { default as Portrythm } from "./defaults/Portrythm.json";
export { default as Pumpdriver } from "./defaults/Pumpdriver.json";
export { default as RobotEmpire } from "./defaults/Robot Empire.json";
export { default as Robotspeak } from "./defaults/Robotspeak.json";
export { default as RubberDuck } from "./defaults/Rubber Duck.json";
export { default as Scoooping } from "./defaults/Scoooping.json";
export { default as Squelf } from "./defaults/Squelf.json";
export { default as StabbyBass } from "./defaults/StabbyBass.json";
export { default as StomachWave } from "./defaults/StomachWave.json";
export { default as Stonecold } from "./defaults/Stonecold.json";
export { default as Syncwave } from "./defaults/Syncwave.json";
export { default as TechStab } from "./defaults/Tech Stab.json";
export { default as TeeVeeSaw } from "./defaults/TeeVeeSaw.json";
export { default as TronIines } from "./defaults/TronIines.json";
export { default as Werq } from "./defaults/Werq.json";

// DEFAULTS FOLDER END ^
