export { default as afxAcid } from "../patches/<afx acid3>.json";
export { default as injection } from "../patches/Injection.json";
export { default as fake3OSC } from "../patches/Fake3OSC.json";
export { default as TeeVeeSaw } from "../patches/TeeVeeSaw.json";
export { default as fifthSaw } from "../patches/dutch-bass/5th Saw.json";
export { default as Delayed } from "../patches/dutch-bass/Delayed.json";
export { default as LeidenLoop } from "../patches/dutch-bass/Leiden Loop.json";
export { default as ShapeShifter } from "../patches/dutch-bass/ShapeShifter.json";
export { default as VintageKit } from "../patches/dutch-bass/Vintage Kit.json";
export { default as NinetiesClassic } from "../patches/dutch-bass/90'S Classic.json";
export { default as DeltaBass } from "../patches/dutch-bass/Delta Bass.json";
export { default as MiniBass } from "../patches/dutch-bass/Mini Bass.json";
export { default as SimpleBeat } from "../patches/dutch-bass/Simple Beat.json";
export { default as VinylPulse } from "../patches/dutch-bass/Vinyl Pulse.json";
export { default as AcidVox } from "../patches/dutch-bass/Acid Vox.json";
export { default as DutchClassic } from "../patches/dutch-bass/DutchClassic.json";
export { default as MotorMouth } from "../patches/dutch-bass/Motor Mouth.json";
export { default as SoulFood } from "../patches/dutch-bass/Soul Food.json";
export { default as VocalChordz } from "../patches/dutch-bass/Vocal Chordz.json";
export { default as AnalogDrums } from "../patches/dutch-bass/Analog Drums.json";
export { default as ElectroKit } from "../patches/dutch-bass/Electro Kit.json";
export { default as MrMatrix } from "../patches/dutch-bass/Mr Matrix.json";
export { default as SyntheBass } from "../patches/dutch-bass/Synthe Bass.json";
export { default as Boogie80s } from "../patches/dutch-bass/Boogie 80's.json";
export { default as FunkyAcid } from "../patches/dutch-bass/Funky Acid.json";
export { default as PortaBass } from "../patches/dutch-bass/Porta Bass.json";
export { default as TechNoir } from "../patches/dutch-bass/Tech Noir.json";
export { default as DanceBass } from "../patches/dutch-bass/Dance Bass.json";
export { default as GrittySquare } from "../patches/dutch-bass/GrittySquare.json";
export { default as PunkFunk } from "../patches/dutch-bass/Punk Funk.json";
export { default as VCTenVox } from "../patches/dutch-bass/VC-10 Vox.json";
export { default as DeepHouse } from "../patches/dutch-bass/Deep House.json";
export { default as KeycityBass } from "../patches/dutch-bass/Keycity Bass.json";
export { default as RawBass } from "../patches/dutch-bass/Raw Bass.json";
export { default as VideoGame } from "../patches/dutch-bass/Video Game.json";
